services:
    bot:
        build: .
        container_name: bhh-bot_v2
        environment:
            - TZ=Europe/Berlin
        restart: unless-stopped
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:latest
        container_name: bhh-bot_v2_db
        restart: unless-stopped
        command: --init-file /data/application/init.sql
        env_file:
            - .env
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./utils/db/sql/init.sql:/data/application/init.sql
            - ./utils/db/sql/data:/var/lib/mysql